name: Merge to main and Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  merge-to-main-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Merge pull request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          commit-message: "Merge pull request"
          title: "Merge pull request"
          branch: main
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
