name: Merge Branches

on:
  pull_request:
    branches:
      - main

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Merge Branches
        run: |
          git merge --no-ff ikram
          git merge --no-ff awais
          git push origin main
