name: Merge Ikram and Awais Branches to Main

on:
  push:
    branches:
      - ikram
      - awais

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the application
        run: |
          python main.py

  merge-to-main:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Merge branches to main
        run: |
          git checkout main
          git merge ikram
          git merge awais
          
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Merge Ikram and Awais branches to main"
          commit_options: "--no-verify"
          commit_user_name: "github-actions"
          commit_user_email: "github-actions@github.com"
