name: Merge Branches

on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge branches
        run: |
          git checkout main
          git merge --no-ff ikram awais
          git push
